//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineLauncher.Properties.Strings.ru", typeof(Strings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти в аккаунт.
        /// </summary>
        public static string Account_Login {
            get {
                return ResourceManager.GetString("Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из аккаунта.
        /// </summary>
        public static string Account_Logout {
            get {
                return ResourceManager.GetString("Account_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верификация....
        /// </summary>
        public static string Action_Fetching {
            get {
                return ResourceManager.GetString("Action_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить.
        /// </summary>
        public static string Action_Install {
            get {
                return ResourceManager.GetString("Action_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть.
        /// </summary>
        public static string Action_Run {
            get {
                return ResourceManager.GetString("Action_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить.
        /// </summary>
        public static string Action_Stop {
            get {
                return ResourceManager.GetString("Action_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Браузер.
        /// </summary>
        public static string JavaBrowser_Title {
            get {
                return ResourceManager.GetString("JavaBrowser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка поиска загрузчика.
        /// </summary>
        public static string Progress_Error_Loader {
            get {
                return ResourceManager.GetString("Progress_Error_Loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устанавливаем Майнкрафт: {0} / {1}.
        /// </summary>
        public static string Progress_InstallingMinecraft {
            get {
                return ResourceManager.GetString("Progress_InstallingMinecraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устанавливаем сборку: {0} / {1}.
        /// </summary>
        public static string Progress_InstallingModpack {
            get {
                return ResourceManager.GetString("Progress_InstallingModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка....
        /// </summary>
        public static string Progress_Preparing {
            get {
                return ResourceManager.GetString("Progress_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновляем сборку: {0} / {1}.
        /// </summary>
        public static string Progress_UpdatingModpack {
            get {
                return ResourceManager.GetString("Progress_UpdatingModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Директория установки.
        /// </summary>
        public static string Setting_InstallDir {
            get {
                return ResourceManager.GetString("Setting_InstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к Java.
        /// </summary>
        public static string Setting_JavaPath {
            get {
                return ResourceManager.GetString("Setting_JavaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. RAM (MB).
        /// </summary>
        public static string Setting_MaxRAM {
            get {
                return ResourceManager.GetString("Setting_MaxRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин. RAM (MB).
        /// </summary>
        public static string Setting_MinRAM {
            get {
                return ResourceManager.GetString("Setting_MinRAM", resourceCulture);
            }
        }
    }
}
