//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineLauncher.Properties.Strings.ru", typeof(Strings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти в аккаунт.
        /// </summary>
        public static string Account_Login {
            get {
                return ResourceManager.GetString("Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из аккаунта.
        /// </summary>
        public static string Account_Logout {
            get {
                return ResourceManager.GetString("Account_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть.
        /// </summary>
        public static string Play_Title {
            get {
                return ResourceManager.GetString("Play_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Директория установки.
        /// </summary>
        public static string Setting_InstallDir {
            get {
                return ResourceManager.GetString("Setting_InstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к Java.
        /// </summary>
        public static string Setting_JavaPath {
            get {
                return ResourceManager.GetString("Setting_JavaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. RAM (MB).
        /// </summary>
        public static string Setting_MaxRAM {
            get {
                return ResourceManager.GetString("Setting_MaxRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин. RAM (MB).
        /// </summary>
        public static string Setting_MinRAM {
            get {
                return ResourceManager.GetString("Setting_MinRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }
    }
}
